### ISSUE TITLE
the command without "--take-snapshot" is not taking any screenshots

### ISSUE THREAD

**Issue by prasadmudedla** [agave/testcafe-blink-diff#1]
1. running this "npx testcafe chrome:headless tests/e2e/cases -s tests/screenshots --take-snapshot" gives base screenshots (We have base images after this point)
2. running this "npx testcafe chrome:headless tests/e2e/cases -s tests/screenshots" is not taking any screenshots (we do not have actual images even after this run)

**Comment by pateketrueke** [comment]
That's intended that way, you MUST pass `--take-snapshot` if you want take actual screenshots.

Without that flag the module simply does nothing:

```js
 takeSnapshot: isTakeSnapshot === -1 ? noop : takeSnapshot,
```

Source: https://github.com/agave/testcafe-blink-diff/blob/master/lib/index.js#L116

**Comment by prasadmudedla** [comment]
I have tried to follow the ReadME. could you please update the README accordingly.

**Comment by pateketrueke** [comment]
Yeah, sorry I noticed that, thanks for your feedback!

**Comment by prasadmudedla** [comment]
Thank you so much for the quick help. This helped me a lot.
